# Generated by Django 3.1.1 on 2021-03-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210325_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskauthorization',
            old_name='billable',
            new_name='is_billable',
        ),
    ]
