# Generated by Django 3.1.1 on 2021-04-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210325_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargecode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='task_authorization',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskauthorization',
            name='charge_code',
        ),
        migrations.RemoveField(
            model_name='taskauthorization',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaxLocation',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ChargeCode',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='TaskAuthorization',
        ),
    ]
