# Generated by Django 3.1.1 on 2021-04-01 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargecode', '0001_initial'),
        ('account', '0002_profile_billable_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_allocated', models.FloatField(default=1.0)),
                ('hours_spent', models.FloatField(blank=True, null=True)),
                ('hours_remaining', models.FloatField(blank=True, null=True)),
                ('hours_percentage', models.FloatField(blank=True, null=True)),
                ('billable_percentage', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ta_file', models.FileField(blank=True, null=True, upload_to='')),
                ('is_billable', models.BooleanField(blank=True, default=False, null=True)),
                ('charge_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chargecode.chargecode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
